### ISSUE TITLE
Add `font-display: swap` to font-face blocks

### ISSUE THREAD

**Issue by maxsteenbergen** [indestructible-type/Jost#54]
Basically the title says it all. If each @font-face block in the `Jost.css` file would have the rule `font-display: swap` added, it would improve site accessibility and Lighthouse scores. I'd make a PR, but can't find the css file.

For reference sake, here's what I mean for a single @font-face:

```css
@font-face {
  font-family: "Jost";
  src: url("Jost-100.ttf") format("truetype");
  font-weight: 100;
  font-style: normal;
  font-display: swap;
}
```

Thanks!
